第一稿の作成
extreal-dev/extreal-r3f-guide pull request #1
Opened 2024-04-09 08:48 UTC by t-shimoda

# 何の変更を加えましたか？
- トップページの更新（ 11afdfd ）
- 全体のイントロダクションの章 （ d0ff873 ）
- サンプルアプリケーションの章 （ 7a5cb74 ）
- Learningの章 （ afdc67c ）

# 何を確認しましたか?

- [x] 変更したページと影響がありそうなページをブラウザで確認しました
- N/A 日本語と英語のページが一致していることを確認しました
- [x] リンクや画像のファイルパスは拡張子付きの相対パスになっていることを確認しました
  - [Link docs by file paths](https://docusaurus.io/docs/next/versioning#link-docs-by-file-paths)
  - [Global or versioned collocated assets](https://docusaurus.io/docs/next/versioning#global-or-versioned-collocated-assets)(using per-version)
- [x] categoryページ(category/release等)への相対リンクが現在のバージョンのページに遷移することを確認しました

# レビュアーへのメッセージ

2024-04-10 08:07 UTC, sus-taguchi-t submitted a review, later dismissed

2024-04-10 08:07 UTC, sus-taguchi-t commented on .github/pull_request_template.md
書く場所がなかったのでこちらに記載します。
package.json の中身についてです。
`@docusaurus/theme-mermaid` のバージョン指定を固定にした方が良いと思います。

というのも他の `@docusaurus/xxxx` はすべてバージョン固定なのに対して `@docusaurus/theme-mermaid` のみキャレット `^` で指定されていたため `yarn` コマンドのときに依存パッケージ間でバージョニングの齟齬が生じていました。
結果として `yarn start` 時にエラーで落ちています。

2024-04-10 08:07 UTC, sus-taguchi-t commented on docs/intro.md
> +画するための React Three Fiber というライブラリを使用して、XR を実現するための知識や技術をまとめたコンテンツを公開しています。
文中で改行しない方が良いと思います。
ビルドした際に半角スペースが挿入されて表示されてしまっています。

2024-04-10 08:07 UTC, sus-taguchi-t commented on docs/intro.md
> +3 次元に付随する描画や動画再生を通常の Web 技術の延長線上で行うことで、専用のエディタを必要としない、普通の Web 開発環境での開発が行えるようになります。
冒頭の文と重複してしまっているのが気になります。
冒頭で R3F について説明してから「このサイトは R3F を使用して～」と始めると分かりやすくなると思います。

2024-04-10 08:07 UTC, sus-taguchi-t commented on docs/intro.md
R3F を用いた Extreal の基本方針やグランドデザインのようなものがあればここで説明していただくと内容が頭に入りやすいと思います。

2024-04-10 08:07 UTC, sus-taguchi-t commented on docs/intro.md
> +現在、マルチプレイやボイスチャットができるサンプルアプリケーションをリファレンス実装としても公開しています。
現在提供しているものはリストにすると見やすくなると思います。
以下は一例です。

- サンプルアプリ
  - マルチプレイやボイスチャットができるサンプルアプリケーション
- ラーニング
  - R3F の使い方を学習する教材
- ガイド
  - R3F を使用して XR を実現するための知識や技術を案内するガイド

2024-04-10 08:07 UTC, sus-taguchi-t commented on docs/intro.md
> +現在、マルチプレイやボイスチャットができるサンプルアプリケーションをリファレンス実装としても公開しています。
コンテンツとしてリファレンスのみだと魅力が弱いと思ったので、今後の展望等があれば info として記載すると良いかなと思います。

2024-04-10 08:07 UTC, sus-taguchi-t commented on docs/sample-app/01-intro.md
サンプルアプリの魅力があまり伝わらないように感じました。
このサンプルアプリがどのように活用できるかを書くと良いと思います。

2024-04-10 08:07 UTC, sus-taguchi-t commented on docs/sample-app/01-intro.md
目次の Sample Application 以下の各ページでどのような内容を提供しているかを書くと良いと思います。

2024-04-10 08:07 UTC, sus-taguchi-t commented on docs/sample-app/01-intro.md
実際のコードを見たりアプリを動かしたりしながらガイドを見られるように、GitHub へのリンクを貼ると良いと思います。

2024-04-10 08:07 UTC, sus-taguchi-t commented on docs/sample-app/01-intro.md
> +サンプルアプリケーションは SpotVisit という名前です。アバターを選択し、スポットを訪問できます。
おそらく初めてこのガイドを見る人には「スポット」という単語は通じないかなと思います。

2024-04-10 08:07 UTC, sus-taguchi-t commented on docs/sample-app/03-architecture.md
> +  - 初回起動時は、プロフィール入力画面は強制的に表示されます
Requirement では「アバター選択画面」となっていたので統一した方が良いと思います。

2024-04-10 08:07 UTC, sus-taguchi-t commented on docs/sample-app/03-architecture.md
> +- プロフィール入力画面（ダイアログ）でプレイヤーのニックネームとアバターを選択します
ニックネームとアバターで動詞が異なるのでそれぞれ記述した方が良いと思います。
「プレイヤーのニックネームを入力しアバターを選択します」

2024-04-10 08:07 UTC, sus-taguchi-t commented on docs/sample-app/03-architecture.md
> +![screen-transition](../img/screen-transition.drawio.png)
スポット選択画面からアバター選択画面に戻る（表示する？）ことはできるのでしょうか？
Requirement ではスポット選択画面のところに「アバター選択画面を表示できる」といった記述がなかったので気になりました。

2024-04-10 08:07 UTC, sus-taguchi-t commented on docs/sample-app/04-test-planning.md
> +  - テストケース
テストケースが見当たらないように思うのですが、どこかにあるのでしょうか？

2024-04-10 08:07 UTC, sus-taguchi-t commented on docs/sample-app/02-requirement.md
> +  - 360 度画像または動画を表示できる（動画優先）
気になったので質問です。
「（動画優先）」とはどういうことでしょうか？

2024-04-10 08:07 UTC, sus-taguchi-t commented on docs/sample-app/05-development-guide.md
> +│      ├─InSpot               ... スポット内画面
Requirement では「スポット訪問画面」となっていたので統一した方が良いと思います。

2024-04-10 08:07 UTC, sus-taguchi-t commented on docs/sample-app/05-development-guide.md
> +## Functions
気になったので質問です。
IT 系で「機能」といえば "feature" のイメージを持っていましたが、"function" も一般的に用いられるものなのでしょうか？

2024-04-10 08:07 UTC, sus-taguchi-t commented on docs/sample-app/05-development-guide.md
> +360 度動画の表示は、ビデオを非表示で再生する`<HiddenVideo>`コンポーネントと、360 度球体で表示する`<VideoSphere>`から構成されます。
どうしてこのような実装方法になっているのかが気になります。
理由を一言書いていただけるとより分かりやすくなると思います。

2024-04-10 08:07 UTC, sus-taguchi-t commented on docs/sample-app/05-development-guide.md
> +```
このシーケンス図はメッセージ送信の仕組みのシーケンス図と縦のラベルを揃えるとより分かりやすくなると思います。

2024-04-10 08:07 UTC, sus-taguchi-t commented on docs/learning/01-intro.md
Learning のサブページである「State Management with Zustand」と「Multiplay with Livekit」についても触れると良いと思います。
これらのページがどのような位置づけなのかがイメージしづらかったです。

2024-04-10 08:07 UTC, sus-taguchi-t commented on src/components/HomepageFeatures/index.js
少しこのサイトの魅力が分かりづらかったです。
どのようなことに活用できるか、どのような嬉しいことに繋がるか等が書かれているとこの先のドキュメントまで読みたくなりそうです。

2024-04-12 05:17 UTC, sus-yoshikane-t submitted a review, later dismissed

2024-04-12 05:17 UTC, sus-yoshikane-t commented on docs/learning/02-state-management-with-zustand.md
> +React では、親子関係の状態の受け渡しに props が使われ、それ以外はあるコンポーネント以下で有効になる useContext というフックを使った状態の受け渡しの 2 通りがあります。
受け渡しが並列なので表現が揃うと良いと思いました。(語の入れ替えで間違った文章になってしまっていたらすみません)
```suggestion
React には、props を使った親子関係の状態の受け渡しと、あるコンポーネント以下で有効になる useContext というフックを使った親子関係以外の状態の受け渡しの 2 通りの状態の受け渡しがあります。
```

2024-04-12 05:17 UTC, sus-yoshikane-t commented on docs/sample-app/03-architecture.md
> +- スポット画面では３６０度動画/画像を表示したりマルチプレイ・ボイスチャットを楽しみます
360がここだけ全角になっています。

2024-04-12 05:17 UTC, sus-yoshikane-t commented on docs/learning/03-multiplay-with-livekit.md
> +MultiplayChannelComponent 内で、メッセージ受信の処理（`useDataChannel`の２番目引数のコールバック関数）が`useMultiplayChannelStore`から取得した`channel`にレスポンスをキューするように実装されています。
２番目引数の２が全角になっています。

2024-04-12 05:17 UTC, sus-yoshikane-t commented on docs/learning/03-multiplay-with-livekit.md
> +このように、`channel`をキューとすることで、send と ReceivedDataMessage を受け取るコールバックが１つのコンポーネント内に書けるため、見通しが良くなります。そうしない場合は、送信関数の外部コンポーネントへの引き回しや受信のコールバックを外から指定できるようにすることが必要になります。
１つのコンポーネントの１が全角になっています。

2024-04-12 10:06 UTC, kiyohome requested changes

2024-04-12 10:06 UTC, kiyohome commented on src/pages/index.js
>    const { siteConfig } = useDocusaurusContext();
トップページのFintanロゴのところは現行Extrealに合わせてFintanサイトに遷移させませんか？

2024-04-12 10:06 UTC, kiyohome commented on src/components/HomepageFeatures/index.js
> +          360度画像や360度球体動画の再生、バックエンドのAPIとの疎通、Zustandを使った状態管理、LiveKitを使ったマルチプレイといった実用的なサンプルアプリケーションとその作り方の解説を公開しています。
「360度球体動画」は一般的な言い方でしょうか？
チーム内では単に360度動画ということが多いです。

2024-04-12 10:06 UTC, kiyohome commented on src/components/HomepageFeatures/index.js
> +    title: "Reference for Virtual Communication",
今回はリファレンスなので見出しを3つのコンテンツにして、コンテンツの説明とこんなことができるよ、と伝えるのがいいかと思いました。コンテンツの魅力を伝えるというより、利用者が何ができるのかを伝えるイメージです。

- Sample Application
- Guide
- Learning

2024-04-12 10:06 UTC, kiyohome commented on src/components/HomepageFeatures/index.js
> +          React Three Fiber を使うための基礎的な学習コンテンツを紹介します。
「React Three Fiber を使うための基礎的な学習コンテンツ」
「これからReact、TypeScriptを学びたい方も必要に応じて学ぶことができます」
となると、R3F、React、TypeScriptの学習教材をイメージしましたが、そのあたりは本家や書籍、ネットなど、このコンテンツのスコープ外かと思いますが認識合ってますか？

2024-04-12 10:06 UTC, kiyohome commented on src/pages/index.js
>    const { siteConfig } = useDocusaurusContext();
書くとこ見当たらなかったのでここに書きます。
フッターのTerms of Useをクリックするとエラーになりました。
```
Uncaught runtime errors:
×
ERROR
goTermsOfUse is not defined
ReferenceError: goTermsOfUse is not defined
    at HTMLAnchorElement.onclick (http://localhost:3000/:1:1)
```

2024-04-12 10:06 UTC, kiyohome commented on docusaurus.config.js
> +  tagline: "React Three Fiber(R3F) のナレッジとリファレンス",
「React Three Fiber(R3F) のナレッジとリファレンス」だとXRやコミュニケーションのイメージがなく、WebGLのイメージが強いので、index.jsのdescriptionに書いてた「XR reference with React Three Fiber(R3F)」の方が良いと思います。
R3Fを使ったXRのリファレンスかと思います。

2024-04-12 10:06 UTC, kiyohome commented on docs/intro.md
> +画するための React Three Fiber というライブラリを使用して、XR を実現するための知識や技術をまとめたコンテンツを公開しています。
「React Three Fiber」はドキュメント上、初登場なのでをリンクにしてもよかと思いました。

2024-04-12 10:06 UTC, kiyohome commented on docs/intro.md
> +React Three Fiber（R3F）とは、3 次元描画を行う JavaScript のライブラリ Three.js を React 上で宣言的に記述できるようにしたライブラリです。
「Three.js」も初登場なのでリンクがいいかと思いました。

2024-04-12 10:06 UTC, kiyohome commented on docs/intro.md
> +3 次元に付随する描画や動画再生を通常の Web 技術の延長線上で行うことで、専用のエディタを必要としない、普通の Web 開発環境での開発が行えるようになります。
ここの文章が唐突に感じました。
おそらく前提としている背景事情が何かあってこの説明に繋がるように感じました。

2024-04-12 10:06 UTC, kiyohome commented on docs/intro.md
>  # Introduction
Introductionで下記のようなことを伝えてもいいかなと思いました。

- このコンテンツをなぜ作ったのか？
- このコンテンツが目指しているゴールは？
- ゴール達成のために提供しているコンテンツは？
- コンテンツをどのように活用して欲しいか？

コンテンツ作成側の考えてることを伝えるイメージです。

2024-04-12 10:06 UTC, kiyohome commented on docs/sample-app/02-requirement.md
> +  - PC ブラウザ
スマホブラウザも入れて欲しいです。

2024-04-12 10:06 UTC, kiyohome commented on docs/sample-app/03-architecture.md
> +![system-structure](../img/system-structure.drawio.png)
Marmeidで直接書いた方がメンテナンスが楽なのでUnityのガイドはそうしてますが、合わせませんか？
https://docusaurus.io/docs/next/markdown-features/diagrams

2024-04-12 10:06 UTC, kiyohome commented on docs/sample-app/03-architecture.md
> +  - 初回起動時は、プロフィール入力画面は強制的に表示されます
「プロフィール入力画面は初回起動時に表示、2回目の起動時以降は表示されません。」と明示的に書いた方がよいと思いました。

2024-04-12 10:06 UTC, kiyohome commented on docs/sample-app/03-architecture.md
> +![screen-transition](../img/screen-transition.drawio.png)
アプリのUI、プロダクト並みにもっとカッコよくしたいですね！

2024-04-12 10:06 UTC, kiyohome commented on docs/sample-app/03-architecture.md
> +└─libs                    ... ユーティリティ群
私が慣れてないだけかもですが、libsというとサードパーティのライブラリ利用をイメージしました。
ユーティリティであればutilsでもいいと思いますが、フロントエンドの慣習的にはlibsでしょうか？

2024-04-12 10:06 UTC, kiyohome commented on docs/sample-app/04-test-planning.md
> +  - ESLint による静的解析と prettier による自動整形
最近流行ってそうなBiome使ってみませんか？
https://qiita.com/99no_exit/items/4b880735621d7f7416f3

2024-04-12 10:06 UTC, kiyohome commented on docs/sample-app/04-test-planning.md
> +  - 全件合格、テストカバレッジ 100％
テストカバレッジはどうやって取りますか？
UnityのWebGLの時はChromeの開発者ツールで取ってたのでC0までしか取れず、できればC1まで取りたいと思ってます。

2024-04-12 10:06 UTC, kiyohome commented on docs/sample-app/02-requirement.md
> +  - グループ数の制限なし
P2Pの時にサーバー影響ないのでグループ数を無制限にしてましたが、LiveKitでも無制限にできますか？

2024-04-12 10:06 UTC, kiyohome commented on docs/sample-app/04-test-planning.md
> +  - 同じスポットに 10 人参加した状態で 1.5 時間実行します。
「10 人参加した状態」は「1グループの最大人数が参加した状態」ということですよね？

2024-04-12 10:06 UTC, kiyohome commented on docs/sample-app/04-test-planning.md
> +  - アプリケーションの CPU 使用率/メモリ使用量を監視してデータから合格基準を判断します。
アプリだけでなく、サーバー側のリソースも確認が必要だと思います。
あと、おそらく機能要件のとこでフィードバックしましたがグループ数は制限がかかると思うので、最大グループ数を入れた状態でサーバー側のテストが必要だと思います。

2024-04-12 10:06 UTC, kiyohome commented on docs/sample-app/05-development-guide.md
> +コンポーネントの状態を管理するのに、通常の React の Context と State 以外に、Zustand という状態管理ライブラリを使って複数のコンポーネントにまたがる状態を管理しています。
初回の「Zustand」はリンクだと嬉しいです。

2024-04-12 10:06 UTC, kiyohome commented on docs/sample-app/05-development-guide.md
> +### State Management
アプリの中に何種類か状態があると思いますが、下記のような決め事をしなくてよいでしょうか？

- コンポーネント内の制御に使う状態（ミュート状態とか）：State
- 機能をまたがる状態（アバター名とか）：Zustand
- バックエンドのデータ状態（スポット情報とか）：TanStack Query
- ReactのContextは使いません
みたいな話です。

2024-04-12 10:06 UTC, kiyohome commented on docs/sample-app/05-development-guide.md
> +
実装例も合った方が分かりやすいかと思いました。
SpotVisitから抜粋できないですかね？

2024-04-12 10:06 UTC, kiyohome commented on docs/sample-app/05-development-guide.md
> +
Project StructionにState Management～Responsibility of Componentsが入ってますが、間違いですよね？
全部並列で良いかと思いました。

2024-04-12 10:06 UTC, kiyohome commented on docs/sample-app/05-development-guide.md
> +
全体的な話しとして、エラー処理とサスペンド（やLoading）は章を設けてどうするのか説明入れた方がいいと思います。
共通的な仕組みでやるのかと思ってました。

2024-04-12 10:06 UTC, kiyohome commented on docs/sample-app/05-development-guide.md
> +## Functions
利用状況可視化は入ってないですよ。バックログに入っていれば大丈夫です。

2024-04-12 10:06 UTC, kiyohome commented on docs/sample-app/05-development-guide.md
> +  if (isLoading) {
上でもフィードバックしてますが、このあたり個別に書かなくてもいいかと考えてましたが、R3Fだと共通化が難しいですか？
https://zenn.dev/shunta_shirai/articles/f96add83b23ba7

2024-04-12 10:06 UTC, kiyohome commented on docs/sample-app/05-development-guide.md
> +`useSpots()`の実装は以下の通りで、[Oval](https://orval.dev/overview)を利用した自動生成コード`useGetSpots()`を呼び出しているだけです。
Ovalを使ってバックエンドの呼び出しコードを自動生成することもガイドに書いた方がよくないでしょうか？

2024-04-12 10:06 UTC, kiyohome commented on docs/sample-app/05-development-guide.md
> +<>
これを1つのコンポーネントにするのは難しいですか？と思いました。

2024-04-12 10:06 UTC, kiyohome commented on docs/learning/01-intro.md
> +React を学ぶには JavaScript の言語知識が必須です。 JavaScript を触れたことがない人は、まずは JavaScript の知識習得からお願いします。
「まずは JavaScript の知識習得からお願いします」
お願いします→始めましょう
とかでどうでしょうか。

2024-04-12 10:06 UTC, kiyohome commented on docs/sample-app/05-development-guide.md
> +### Multiplay with LiveKit
同じ階層の見出しでここだけ英語なのが気になりました。

2024-04-12 10:06 UTC, kiyohome commented on docs/learning/01-intro.md
> +### Three.js
https://threejs-journey.com/
有料ですがここもいいです。

2024-04-16 00:13 UTC, kiyohome requested changes

2024-04-16 00:13 UTC, kiyohome commented on docs/sample-app/05-development-guide.md
> +### Responsibility of Components
画面遷移をどのように実装するのかも共通の仕組みだと思うので書いておいて欲しいです。

2024-04-16 00:13 UTC, kiyohome commented on docs/sample-app/05-development-guide.md
> +
2DのUI（アバター選択や名前入力など）と3Dの機能の典型的な実装方法の説明が欲しいと思いました。
構造、状態、相互作用が分かるようなものをイメージしています。

2024-04-19 04:42 UTC, t-shimoda commented on docs/sample-app/05-development-guide.md
> +## Functions
Featureは広義の意味での機能で、どちらかというと「特徴」という意味が強いです。
ですので、このページではFunctionsとしています

2024-04-24 04:27 UTC, t-shimoda commented on docs/intro.md
> +画するための React Three Fiber というライブラリを使用して、XR を実現するための知識や技術をまとめたコンテンツを公開しています。
修正しました d319ca952acfb6fee9f719d7e342ad3b0ab2d847

2024-04-24 04:27 UTC, t-shimoda commented on docs/intro.md
> +3 次元に付随する描画や動画再生を通常の Web 技術の延長線上で行うことで、専用のエディタを必要としない、普通の Web 開発環境での開発が行えるようになります。
修正しました d319ca952acfb6fee9f719d7e342ad3b0ab2d847

2024-04-24 04:28 UTC, t-shimoda commented on docs/intro.md
> +現在、マルチプレイやボイスチャットができるサンプルアプリケーションをリファレンス実装としても公開しています。
修正しました d319ca952acfb6fee9f719d7e342ad3b0ab2d847

2024-04-24 04:29 UTC, t-shimoda commented on docs/sample-app/03-architecture.md
> +- スポット画面では３６０度動画/画像を表示したりマルチプレイ・ボイスチャットを楽しみます
修正しました 2c7853b0ecc3c48876b62281c380b305843d440f

2024-04-24 04:29 UTC, t-shimoda commented on docs/learning/03-multiplay-with-livekit.md
> +MultiplayChannelComponent 内で、メッセージ受信の処理（`useDataChannel`の２番目引数のコールバック関数）が`useMultiplayChannelStore`から取得した`channel`にレスポンスをキューするように実装されています。
修正しました 2c7853b0ecc3c48876b62281c380b305843d440f

2024-04-24 04:29 UTC, t-shimoda commented on docs/learning/03-multiplay-with-livekit.md
> +このように、`channel`をキューとすることで、send と ReceivedDataMessage を受け取るコールバックが１つのコンポーネント内に書けるため、見通しが良くなります。そうしない場合は、送信関数の外部コンポーネントへの引き回しや受信のコールバックを外から指定できるようにすることが必要になります。
修正しました 2c7853b0ecc3c48876b62281c380b305843d440f

2024-04-24 04:30 UTC, t-shimoda commented on docs/learning/01-intro.md
> +React を学ぶには JavaScript の言語知識が必須です。 JavaScript を触れたことがない人は、まずは JavaScript の知識習得からお願いします。
修正しました d3141c3567acfb3137cb5a9ceba9f5bedbe8d20b

2024-04-24 04:34 UTC, t-shimoda commented on docs/sample-app/05-development-guide.md
> +```
向きが変わるので現状のままとしています。対称性（向きが逆になる）より、読み込む向き（左から右）を大事にしています。

2024-04-24 04:48 UTC, t-shimoda commented on src/components/HomepageFeatures/index.js
> +          360度画像や360度球体動画の再生、バックエンドのAPIとの疎通、Zustandを使った状態管理、LiveKitを使ったマルチプレイといった実用的なサンプルアプリケーションとその作り方の解説を公開しています。
360度動画に修正しました 3c4992547a3d4d72fab85c69bb907fa09fcce4d8

2024-04-24 04:49 UTC, t-shimoda commented on docs/sample-app/05-development-guide.md
> +360 度動画の表示は、ビデオを非表示で再生する`<HiddenVideo>`コンポーネントと、360 度球体で表示する`<VideoSphere>`から構成されます。
確かにわかりにくい構成となっているのは背景があるからです。その理由を追記しました。  f754e292bd0dea7e4a763369e987e302f0f20e52

（後の個別の説明と被るところもありくどくなっているかもしれません）

2024-04-24 05:14 UTC, t-shimoda commented on docs/sample-app/05-development-guide.md
> +<>
現状、難しいです。DreiのHtmlタグを使えばできるかもしれませんので調査します。

2024-04-24 05:18 UTC, t-shimoda commented on docs/sample-app/01-intro.md
不要と考えます。SampleAppliationが出ると、最初の1行が表示されるので、すでに説明がわかるような1行目を書いています。
<img width="863" alt="image" src="https://github.com/extreal-dev/extreal-r3f-guide/assets/25521540/173b76e5-d2a3-40c9-9028-24e59a28283a">

2024-04-24 05:28 UTC, t-shimoda commented on docs/sample-app/05-development-guide.md
> +│      ├─InSpot               ... スポット内画面
修正しました 9ba51dbc67eb63b4cdbb59fe4ca307445e16f08b

2024-04-24 05:29 UTC, t-shimoda commented on docs/sample-app/05-development-guide.md
> +### Multiplay with LiveKit
修正しました 8de4fbb01dea7ecc61dbca8fb86d86df34f43959

2024-04-24 05:31 UTC, t-shimoda commented on docs/intro.md
現状リファレンス実装とその解説のみなので、基本方針やコンポーネント図などはありません。

2024-04-24 05:34 UTC, t-shimoda commented on docs/sample-app/01-intro.md
> +サンプルアプリケーションは SpotVisit という名前です。アバターを選択し、スポットを訪問できます。
直後に説明があるので通じると思います。
> スポットでは 360 度画像が表示されるか動画が再生され、その中を自身の分身であるアバターで自由に動くことができます。

2024-04-24 05:36 UTC, t-shimoda commented on docs/sample-app/03-architecture.md
> +  - 初回起動時は、プロフィール入力画面は強制的に表示されます
プロフィール入力画面に統一しました。 30ab0b754c749f95cc54c5111cfa3b6153345bea

2024-04-24 05:39 UTC, t-shimoda commented on docs/sample-app/03-architecture.md
> +- プロフィール入力画面（ダイアログ）でプレイヤーのニックネームとアバターを選択します
修正しました 83b165e3906f47dfe8232abf1f23f8662d43bc6e

2024-04-24 05:40 UTC, t-shimoda commented on docs/sample-app/03-architecture.md
> +![screen-transition](../img/screen-transition.drawio.png)
できます。追記しました https://github.com/extreal-dev/extreal-r3f-guide/pull/1/commits/30ab0b754c749f95cc54c5111cfa3b6153345bea#diff-c6680da433c24c2b85731ff84e9e5797f61984684d0aef5a2ee51bbef1fb8f15R30

2024-04-24 05:43 UTC, t-shimoda commented on docs/sample-app/04-test-planning.md
> +  - テストケース
手動テストのテストケースはこのリファレンスでは不要と考え、削除しました e143f7f7ab1aa9e9e4775de8f9a8b02fd71cd092

2024-04-24 05:45 UTC, t-shimoda commented on docs/sample-app/02-requirement.md
> +  - 360 度画像または動画を表示できる（動画優先）
動画と画像が両方SpotInfoというレスポンスにあれば動画優先という意味ですが、内部仕様でしかないので、記述を削除、動画→画像の順の記述に変更しました。
a308337dabc9734407c526cf4a76ebda50d11b4b

2024-04-24 05:47 UTC, t-shimoda commented on docs/learning/01-intro.md
Learningの目次を左フレームで選択されると、以下の1行説明も表示されるので、Introductionでも言及は不要と考えます。（この1行表示の機能でもわかる1文をあえて、先頭に書いています）
「…」の省略もマウスをホバーさせれば出るので十分だと思います。

<img width="670" alt="image" src="https://github.com/extreal-dev/extreal-r3f-guide/assets/25521540/032b3c71-232a-40eb-ada2-590c4c396055">

2024-04-24 05:52 UTC, t-shimoda commented on docs/sample-app/05-development-guide.md
> +### Responsibility of Components
画面遷移はこのリファレンスではスコープ外としています。フレームワーク（NextjsならApp Router、Remix、ViteならReact Routerを使うことになります）と同梱されているので、セットで使うことになります。

その記述であれば入れることはできますが、入れたほうがよいでしょうか？

2024-04-24 05:55 UTC, t-shimoda commented on docs/learning/01-intro.md
> +### Three.js
ありがとうございます。追加しました d72d9635dabe4e134fe693dcfb47f583141b8b0c

2024-04-24 05:57 UTC, t-shimoda commented on .github/pull_request_template.md
パッケージマネージャにDocusaurusが採用している yarn ではなく、npm run startを使うので問題ありませんでした。
Readmeでも、Nodejsの標準パッケージマネージャのnpmを使うように記述を変えます。

2024-04-24 05:59 UTC, t-shimoda commented on docs/sample-app/01-intro.md
サンプル公開後にリンクを追記します

2024-04-24 06:01 UTC, t-shimoda commented on src/components/HomepageFeatures/index.js
こちらの指摘と合わせて対応します
https://github.com/extreal-dev/extreal-r3f-guide/pull/1#discussion_r1562211341

2024-04-25 00:43 UTC, sus-taguchi-t commented on docs/intro.md
> +画するための React Three Fiber というライブラリを使用して、XR を実現するための知識や技術をまとめたコンテンツを公開しています。
確認しました。

2024-04-25 00:45 UTC, sus-taguchi-t commented on docs/intro.md
> +3 次元に付随する描画や動画再生を通常の Web 技術の延長線上で行うことで、専用のエディタを必要としない、普通の Web 開発環境での開発が行えるようになります。
確認しました。

2024-04-25 01:08 UTC, sus-taguchi-t commented on docs/intro.md
> +現在、マルチプレイやボイスチャットができるサンプルアプリケーションをリファレンス実装としても公開しています。
段落が下がった部分の末尾が統一されていないのが気になりました。
体言で止めるか述語で締めるかを統一した方が良いと思います。

>マルチプレイやボイスチャットができるサンプルアプリケーションです。

> リファレンス実装に沿った機能を実現する方法を解説したガイド

2024-04-25 01:11 UTC, sus-taguchi-t commented on docs/sample-app/01-intro.md
盲点でした。
確かに問題ないと思いました。

2024-04-25 01:12 UTC, sus-taguchi-t commented on docs/sample-app/01-intro.md
分かりました。

2024-04-25 01:18 UTC, sus-taguchi-t commented on docs/sample-app/01-intro.md
> +サンプルアプリケーションは SpotVisit という名前です。アバターを選択し、スポットを訪問できます。
分かりました。

2024-04-25 01:21 UTC, sus-taguchi-t commented on docs/sample-app/03-architecture.md
> +  - 初回起動時は、プロフィール入力画面は強制的に表示されます
確認しました。

2024-04-25 01:22 UTC, sus-taguchi-t commented on docs/sample-app/03-architecture.md
> +- プロフィール入力画面（ダイアログ）でプレイヤーのニックネームとアバターを選択します
確認しました。

2024-04-25 01:23 UTC, sus-taguchi-t commented on docs/sample-app/03-architecture.md
> +![screen-transition](../img/screen-transition.drawio.png)
確認しました。

2024-04-25 01:24 UTC, sus-taguchi-t commented on docs/sample-app/04-test-planning.md
> +  - テストケース
確認しました。

2024-04-25 01:24 UTC, sus-taguchi-t commented on docs/sample-app/02-requirement.md
> +  - 360 度画像または動画を表示できる（動画優先）
分かりました。ありがとうございます！
確認しました。

2024-04-25 01:25 UTC, sus-taguchi-t commented on docs/sample-app/05-development-guide.md
> +│      ├─InSpot               ... スポット内画面
確認しました。

2024-04-25 01:26 UTC, sus-taguchi-t commented on docs/sample-app/05-development-guide.md
> +## Functions
理解しました。ありがとうございます！

2024-04-25 01:28 UTC, sus-taguchi-t commented on docs/sample-app/05-development-guide.md
> +360 度動画の表示は、ビデオを非表示で再生する`<HiddenVideo>`コンポーネントと、360 度球体で表示する`<VideoSphere>`から構成されます。
ありがとうございます！
理解できました。

2024-04-25 01:29 UTC, sus-taguchi-t commented on docs/sample-app/05-development-guide.md
> +```
分かりました。

2024-04-25 01:29 UTC, sus-taguchi-t commented on docs/learning/01-intro.md
盲点でした。
このままで良いと思います。

2024-04-25 01:30 UTC, sus-taguchi-t commented on src/components/HomepageFeatures/index.js
分かりました。

2024-04-25 01:35 UTC, sus-taguchi-t commented on docs/intro.md
分かりました。

2024-04-26 01:42 UTC, sus-yoshikane-t commented on docs/sample-app/03-architecture.md
> +- スポット画面では３６０度動画/画像を表示したりマルチプレイ・ボイスチャットを楽しみます
確認しました。

2024-04-26 01:42 UTC, sus-yoshikane-t commented on docs/learning/03-multiplay-with-livekit.md
> +MultiplayChannelComponent 内で、メッセージ受信の処理（`useDataChannel`の２番目引数のコールバック関数）が`useMultiplayChannelStore`から取得した`channel`にレスポンスをキューするように実装されています。
確認しました。

2024-04-26 01:42 UTC, sus-yoshikane-t commented on docs/learning/03-multiplay-with-livekit.md
> +このように、`channel`をキューとすることで、send と ReceivedDataMessage を受け取るコールバックが１つのコンポーネント内に書けるため、見通しが良くなります。そうしない場合は、送信関数の外部コンポーネントへの引き回しや受信のコールバックを外から指定できるようにすることが必要になります。
確認しました。

2024-04-26 04:49 UTC, kiyohome commented on docs/sample-app/05-development-guide.md
> +### Responsibility of Components
先ほど口頭で会話した、ルーティング使わず1つのパスで状態に応じて画面を出し分けること、のみ追記しておきましょう。

2024-04-26 06:14 UTC, t-shimoda commented on src/pages/index.js
>    const { siteConfig } = useDocusaurusContext();
Fintanへのリンクを追加しました 50796e7ce3df740b0ce78fe2b189b30e63432b7b

2024-04-26 06:15 UTC, t-shimoda commented on docs/learning/02-state-management-with-zustand.md
> +React では、親子関係の状態の受け渡しに props が使われ、それ以外はあるコンポーネント以下で有効になる useContext というフックを使った状態の受け渡しの 2 通りがあります。
語の順序をそろえました。ご提案の文章だと意味が少し変わるので私のほうで修正しました。
ec8f965ee9f9b7a5a6548b7f7f3ac28c4616266f

2024-04-26 06:15 UTC, t-shimoda commented on docs/intro.md
> +現在、マルチプレイやボイスチャットができるサンプルアプリケーションをリファレンス実装としても公開しています。
修正しました d0f4377905b0c6991add72aa4733040a3c327ecd

2024-04-26 08:11 UTC, t-shimoda commented on src/components/HomepageFeatures/index.js
> +    title: "Reference for Virtual Communication",
コンテンツとできることベースに記述を直しました 
54e86f756b770bdd1e241ce68130126cd379d9ec

2024-04-26 08:11 UTC, t-shimoda commented on src/components/HomepageFeatures/index.js
> +          React Three Fiber を使うための基礎的な学習コンテンツを紹介します。
スコープ外でしたので、上記指摘と同時に修正しました
54e86f756b770bdd1e241ce68130126cd379d9ec

2024-04-26 08:48 UTC, t-shimoda commented on docs/sample-app/05-development-guide.md
> +### Responsibility of Components
修正しました。 
8b97588dba526aa6c22ef9feccd8644eaf274bdb

2024-04-30 06:06 UTC, t-shimoda commented on src/pages/index.js
>    const { siteConfig } = useDocusaurusContext();
修正しました 002cc1970ead1716ab6718cceb43e5a5832cebda

2024-04-30 06:24 UTC, t-shimoda commented on docs/sample-app/05-development-guide.md
> +`useSpots()`の実装は以下の通りで、[Oval](https://orval.dev/overview)を利用した自動生成コード`useGetSpots()`を呼び出しているだけです。
「React QueryとOpenAPI定義ファイルからのコード自動生成ツールOrvalを使ったWebアプリケーション開発」
https://fintan.jp/page/4857/
に解説があるので、そちらへの誘導を追記しました。37b13e4a4ea3e31fd8273fe0bf7d57bd4ab14721

2024-04-30 08:36 UTC, t-shimoda commented on .github/pull_request_template.md
修正しました  3c84e20cc6b68c1c70b46dfffe1b0adf3444eda1

2024-05-01 00:28 UTC, t-shimoda commented on docs/intro.md
> +画するための React Three Fiber というライブラリを使用して、XR を実現するための知識や技術をまとめたコンテンツを公開しています。
リンクにしました https://github.com/extreal-dev/extreal-r3f-guide/pull/1/commits/d319ca952acfb6fee9f719d7e342ad3b0ab2d847#diff-22760d417a52c66f14bee182587d458d0737a616dd14cb09748b4c725fc5809fR7

2024-05-01 00:29 UTC, t-shimoda commented on docs/intro.md
> +React Three Fiber（R3F）とは、3 次元描画を行う JavaScript のライブラリ Three.js を React 上で宣言的に記述できるようにしたライブラリです。
リンクにしました。 https://github.com/extreal-dev/extreal-r3f-guide/pull/1/commits/d319ca952acfb6fee9f719d7e342ad3b0ab2d847#diff-22760d417a52c66f14bee182587d458d0737a616dd14cb09748b4c725fc5809fR7

2024-05-01 00:48 UTC, t-shimoda commented on docs/sample-app/03-architecture.md
> +└─libs                    ... ユーティリティ群
その他が入る可能性があるためlibsにしています

2024-05-01 00:49 UTC, t-shimoda commented on docs/sample-app/04-test-planning.md
> +  - ESLint による静的解析と prettier による自動整形
エコシステム（VSCodeプラグイン等の相性や互換性）のためBiomeは見送ります

2024-05-01 00:51 UTC, t-shimoda commented on docs/sample-app/02-requirement.md
> +  - グループ数の制限なし
制限する方向で記述します

2024-05-01 00:51 UTC, t-shimoda commented on docs/sample-app/04-test-planning.md
> +  - 同じスポットに 10 人参加した状態で 1.5 時間実行します。
その通りです。書き方を統一します

2024-05-01 00:52 UTC, t-shimoda commented on docs/sample-app/05-development-guide.md
> +コンポーネントの状態を管理するのに、通常の React の Context と State 以外に、Zustand という状態管理ライブラリを使って複数のコンポーネントにまたがる状態を管理しています。
リンクにしました

2024-05-01 00:54 UTC, t-shimoda commented on docs/sample-app/05-development-guide.md
> +
ガイド内にリンクを張ります。

2024-05-01 00:56 UTC, t-shimoda commented on docs/sample-app/05-development-guide.md
> +
トップレベルにします。

2024-05-01 05:51 UTC, t-shimoda commented on docusaurus.config.js
> +  tagline: "React Three Fiber(R3F) のナレッジとリファレンス",
修正しました a782ea9fefe77335b7b0d20a6c5dfac9457b5eb9

2024-05-01 05:52 UTC, t-shimoda commented on docs/sample-app/03-architecture.md
> +  - 初回起動時は、プロフィール入力画面は強制的に表示されます
修正しました 828739501073f034b073b478082e83a6971fe725

2024-05-01 05:56 UTC, t-shimoda commented on docs/sample-app/05-development-guide.md
> +### State Management
修正しました 03b00c31488f7fc885e10d3f56efa619de65f8c3

2024-05-01 05:59 UTC, t-shimoda commented on docs/sample-app/02-requirement.md
> +  - PC ブラウザ
入れました aee5a41c4154937b0a3db0a58369b10b517c519e

2024-05-01 06:00 UTC, t-shimoda commented on docs/sample-app/05-development-guide.md
> +
6193ee8fc2b04fb5f9e4b2a6cf6c311b0ab0a907

2024-05-01 06:02 UTC, t-shimoda commented on docs/sample-app/03-architecture.md
> +![system-structure](../img/system-structure.drawio.png)
いったん保留とさせてください

2024-05-01 06:07 UTC, t-shimoda commented on docs/sample-app/05-development-guide.md
> +
サスペンドは使いません。サスペンドを使っても結局、下のコードのように個別の対応が必要です。エラー処理は共通化しています。

```
      <ErrorBoundary>
      　　　　// fallbackにはローディング時に表示したい内容を指定する
        <Suspense fallback={<p>Loading profile...</p>}>
          <UserProfile user={resource.user} />
        </Suspense>
      <ErrorBoundary/>
      <ErrorBoundary>
      　　 // Suspenseは非同期処理の境界を定義している。
	// Suspense毎にそれぞれが並行に読み込まれる。
        <Suspense fallback={<p>Loading timeline...</p>}>
          <UserTimeline timeline={resource.timeline} />
        </Suspense>
      <ErrorBoundary/>
````

2024-05-01 06:08 UTC, t-shimoda commented on docs/sample-app/05-development-guide.md
> +  if (isLoading) {
以下のように個別に書く必要はあります。

```
      <ErrorBoundary>
      　　　　// fallbackにはローディング時に表示したい内容を指定する
        <Suspense fallback={<p>Loading profile...</p>}>
          <UserProfile user={resource.user} />
        </Suspense>
      <ErrorBoundary/>
      <ErrorBoundary>
      　　 // Suspenseは非同期処理の境界を定義している。
	// Suspense毎にそれぞれが並行に読み込まれる。
        <Suspense fallback={<p>Loading timeline...</p>}>
          <UserTimeline timeline={resource.timeline} />
        </Suspense>
      <ErrorBoundary/>
```

2024-05-01 06:16 UTC, t-shimoda commented on docs/intro.md
> +現在、マルチプレイやボイスチャットができるサンプルアプリケーションをリファレンス実装としても公開しています。
Infoとして明確に書ける情報はないので保留とさせてください

2024-05-01 06:16 UTC, t-shimoda commented on docs/sample-app/01-intro.md
活用ではなく実際のソースコードの解説をするのがメインです。

2024-05-01 06:31 UTC, t-shimoda commented on docs/sample-app/05-development-guide.md
> +
対応しました  a99a7f233d992efce2146ad6b45d11d5530d5984

2024-05-01 06:43 UTC, t-shimoda commented on docs/sample-app/05-development-guide.md
> +
リンクを張りました  3ec947d19fa57e26b6d361d9beafd8d7b1d06dad

2024-05-01 06:44 UTC, t-shimoda commented on docs/sample-app/04-test-planning.md
> +  - 全件合格、テストカバレッジ 100％
Chromeの開発ツールで測定します。

2024-05-01 07:00 UTC, t-shimoda commented on docs/sample-app/04-test-planning.md
> +  - アプリケーションの CPU 使用率/メモリ使用量を監視してデータから合格基準を判断します。
サーバー側の確認も行いますが、グループ数の最大値はベンチマークテストをしてから決めさせてください
いったん保留としてResolveさせます。

2024-05-01 07:00 UTC, t-shimoda commented on docs/intro.md
>  # Introduction
いったん保留とさせてください

2024-05-01 23:30 UTC, t-shimoda commented on docs/intro.md
> +3 次元に付随する描画や動画再生を通常の Web 技術の延長線上で行うことで、専用のエディタを必要としない、普通の Web 開発環境での開発が行えるようになります。
自然になるよう箇条書きを入れています。

2024-05-02 00:32 UTC, kiyohome approved these changes

2024-05-02 01:39 UTC, merged